# Generated by Django 5.0.7 on 2024-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=100)),
                ('Course_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('lessons', models.CharField(max_length=100)),
                ('instructor_name', models.CharField(max_length=100)),
                ('Categories', models.CharField(max_length=100)),
            ],
        ),
    ]
