# Generated by Django 5.0.7 on 2024-08-31 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coursesection_remove_course_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course_section',
        ),
        migrations.AddField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.coursesection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
