# Generated by Django 5.0.7 on 2024-08-31 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_intro_course_video_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro_course_video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introduction', to='app.course'),
        ),
    ]
