# Generated by Django 5.0.7 on 2024-08-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_intro_course_video_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('duration', models.CharField(max_length=10)),
                ('preview_available', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introduction', to='app.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Intro_course_Video',
        ),
    ]
