# Generated by Django 5.0.7 on 2024-08-31 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_course_conclusion_course_fundamentals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_core_concept',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course_fundamentals',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course_key_features',
            name='course',
        ),
        migrations.RemoveField(
            model_name='intro_content',
            name='course',
        ),
        migrations.CreateModel(
            name='CourseConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('preview_available', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusions', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCoreConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('preview_available', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_concepts', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('preview_available', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseKeyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('preview_available', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='IntroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('preview_available', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_contents', to='app.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Course_conclusion',
        ),
        migrations.DeleteModel(
            name='Course_core_concept',
        ),
        migrations.DeleteModel(
            name='Course_Fundamentals',
        ),
        migrations.DeleteModel(
            name='Course_key_features',
        ),
        migrations.DeleteModel(
            name='Intro_content',
        ),
    ]
