# Generated by Django 5.0.7 on 2024-09-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_enrolledcourse_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('active', 'Active'), ('complete', 'Complete')], default='enrolled', max_length=10),
        ),
    ]
