# Generated by Django 5.0.7 on 2024-09-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(default=1, upload_to='assignments/'),
            preserve_default=False,
        ),
    ]
