# Generated by Django 5.0.7 on 2024-09-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_question_choice_quiz_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconclusion',
            name='url',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursecoreconcept',
            name='url',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursefundamentals',
            name='url',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursekeyfeatures',
            name='url',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='introcontent',
            name='url',
            field=models.TextField(max_length=255),
        ),
    ]
