# Generated by Django 5.0.7 on 2024-09-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_courseconclusion_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
