# Generated by Django 5.0.7 on 2024-09-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='main_image',
            field=models.ImageField(default=1, upload_to='main_image'),
            preserve_default=False,
        ),
    ]
