# Generated by Django 5.0.7 on 2024-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_course_image_course_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='main_image',
            field=models.CharField(max_length=100),
        ),
    ]
